### PR TITLE
Update boto3 and botocore dependencies

### PR DESCRIPTION
**Pull request by Avey777**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
If I can be picky :wink:, having the title of the PR's (which becomes the commit message when the PR is squash-merged) be a bit more informative would be useful for others.

For example, with this PR it could be something like "Update boto3 and botocore dependencies".  Actually, I'll make that change now for this one. :smile:

**Comment by Avey777** [comment]
> If I can be picky 😉, having the title of the PR's (which becomes the commit message when the PR is squash-merged) be a bit more informative would be useful for others.
> 
> For example, with this PR it could be something like "Update boto3 and botocore dependencies". Actually, I'll make that change now for this one. 😄

Cool

**Comment by justinclift** [comment]
That kind of thing is useful when looking at the commit history page for the repo:

https://github.com/RedashCommunity/redash/commits/master

Makes it easier for the person looking for specific changes or a point in time to find it, rather than having to open every commit to look at them one by one. :smile:

**Comment by Avey777** [comment]
I am working hard to rejuvenate redash. Either continuing on the current fork or continuing on the upcoming open-source project on dazdata.com. I don't know which one will be able to thrive, but let's give it our best shot! Open-source is a preferred method for many people.

**Comment by justinclift** [comment]
Oh, maybe the DazData people would be interested in working together in this repo?  Want to ping them and see what the say?

**Comment by Avey777** [comment]
If you are interested in communicating with them, you can join their WeChat group on their official website.

**Pull request merged**
