### PR TITLE
enum parameters add comment as alias

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image
image

For the dropdown list, there should be an alias note for everyone to check.

### CODE REVIEW

**Comment by gaecoli** [comment]
image
image

**Comment by gaecoli** [comment]
@justinclift I will merge it. Do you have any problems?

**Comment by justinclift** [comment]
Go for it. :smile:

The upcoming 10.x images we create should be based on a `release/10.x` or similar branch anyway, which we can look into later.

**Comment by gaecoli** [comment]
> Go for it. 😄
> 
> The upcoming 10.x images we create should be based on a `release/10.x` or similar branch anyway, which we can look into later.

ok

**Comment by justinclift** [comment]
Hmmm, I wonder if any of the people wanting to help out with the new Redash Community - but who haven't joined yet - are good at writing blog posts / docs / similar?

If there are, we could see if they want to create info (for end users) about the user interface changes being made.

Something like the lines of:

```
2023.05.12 This week in Redash

* @gaecoli enhanced `enum` parameters, so [...]
  [ screenshots ]
  Some description of the change goes here (etc)

* [ other changes ]
```

That would probably make things easier for people to understand, and the same screenshots / text could be assembled into more formal documentation at some point.

**Comment by gaecoli** [comment]
> Hmmm, I wonder if any of the people wanting to help out with the new Redash Community - but who haven't joined yet - are good at writing blog posts / docs / similar?
> 
> If there are, we could see if they want to create info (for end users) about the user interface changes being made.
> 
> Something like the lines of:
> 
> ```
> 2023.05.12 This week in Redash
> 
> * @gaecoli enhanced `enum` parameters, so [...]
>   [ screenshots ]
>   Some description of the change goes here (etc)
> 
> * [ other changes ]
> ```
> 
> That would probably make things easier for people to understand, and the same screenshots / text could be assembled into more formal documentation at some point.
> 
> Heh Heh Heh
> 
> I'll move this idea from here to a Discussion somewhere. Need to go shopping first... 😄

I think it's a good idea.

**Comment by justinclift** [comment]
Good reminder.  Just created discussions about it [here](https://github.com/RedashCommunity/redash/discussions/10), and in [the original Redash repo](https://github.com/getredash/redash/discussions/6035).  Lets see how it goes. :smile:

**Pull request merged**
