### PR TITLE
Update requirements_all_ds.txt 

### PR DESCRIPTION
**Pull request by Avey777**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

dql==0.5.26 >> 0.6.2
dynamo3==0.4.10. >> 1.0.0
boto3>=1.10.0,<1.11.0 >> boto3>=1.14.0,<1.15.0
botocore>=1.13,<1.14.0 >> botocore>=1.13,<=1.17.55
#pymapd==0.19.0
## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Cool, looks like you're making progress. :smile:

**Comment by Avey777** [comment]
> Cool, looks like you're making progress. 😄

In order to facilitate future maintenance, we have to abandon some data sources that are no longer being updated so that redash can continue to move forward.

For those who need the previous data sources, they can continue to use the previous older version.

**Comment by Avey777** [comment]
I understand that updates can be unstable. However, for the sake of the future, we have to gradually do these things.

**Comment by Avey777** [comment]
Do we need to consider the supported versions of Python? If we need to support Python 3.10 or even Python 3.11, we may have to drop support for Python versions prior to 3.8.

**Comment by justinclift** [comment]
> In order to facilitate future maintenance, we have to abandon some data sources that are no longer being updated so that redash can continue to move forward.

Yeah, I think that's a reasonable approach for us to take.  Once things are actually working well again in this project, then we could *carefully* look at adding back some of the removed ones *if* certain conditions are met.  Probably something along the lines of "Community Demand + Actively developed library for us to use".  That's my first thought, but who knows how it'll actually end up. :smile:

**Comment by justinclift** [comment]
For now, I'm pretty sure we'd want to keep on supporting Python 3.8.  Ubuntu 20.04 is still under support by Canonical, so we'd probably want to keep Python 3.8 support until Ubuntu 20.04 is End Of Life (EOL).

**Pull request merged**
