### PR TITLE
feat: add query results expired ttl

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

### CODE REVIEW

**Comment by gaecoli** [comment]
#31 #47

**Comment by gaecoli** [comment]
@justinclift I add #31  feat. Maybe can solve #47 problem.

The user can choose to enable the configuration, and the status quo is not enabled by default. If the user enables the query result expiration function, each query will check whether the TTL has been exceeded and re-query. Works well for data from a large number of changing sources used in the enterprise.

**Review by justinclift — APPROVED** [review]
The code itself looks fine. :smile:

**Comment by justinclift** [comment]
@gaecoli Good stuff.  As this introduces two new environment variables, I've just added them to a table on the front page of our wiki:

https://github.com/RedashCommunity/redash/wiki

Ideally we'll put *all* of the environment variables that Redash uses somewhere useful (probably on a dedicated wiki page).  We can likely copy the old Redash knowledge base page as a starting point.

**Comment by gaecoli** [comment]
> @gaecoli Good stuff. As this introduces two new environment variables, I've just added them to a table on the front page of our wiki:
> 
> https://github.com/RedashCommunity/redash/wiki
> 
> Ideally we'll put _all_ of the environment variables that Redash uses somewhere useful (probably on a dedicated wiki page). We can likely copy the old Redash knowledge base page as a starting point.

OK.

**Comment by justinclift** [comment]
I'm adding more environment variables to that page now.  There's a lot that have been added since the [existing Redash page about them](https://redash.io/help/open-source/admin-guide/env-vars-settings) was last updated.

**Comment by gaecoli** [comment]
> I've added a few more environment variables to that page, and will probably do the rest tonight.
> 
> There's a lot that have been added since the [existing Redash page about them](https://redash.io/help/open-source/admin-guide/env-vars-settings) was last updated.

I will help you complete it. Don't worry!

**Pull request merged**
