### PR TITLE
Revert "Add "select all" and "unselect all" to dropdown selects"

### PR DESCRIPTION
**Pull request by justinclift**
Reverts RedashCommunity/redash#39, as it clearly needs more work due to causing our CI to fail.

### CODE REVIEW

**Comment by gaecoli** [comment]
> Reverts #39, as it clearly needs more work due to causing our CI to fail.

ok, i tested it. Just code style not pass.

**Comment by justinclift** [comment]
Cool.  Yeah, if we get the code style testing to pass then we should be good. :smile:

**Comment by gaecoli** [comment]
> 

I will fix it.

**Comment by justinclift** [comment]
Thanks.  My head space is mostly in backend Go programming at the moment, so I'm not much use for Typescript + React changes for now. :smile:

**Pull request merged**
