### PR TITLE
Feature/Add Discord Alert Destination

### PR DESCRIPTION
**Pull request by VitalyVakhteev**
## What type of PR is this? 

- [x] Feature

## Description
Added a new Discord destination that functions similarly to Slack. Asks for a URL (from a webhook) and a name for the destination.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

For manual testing, add a query, add the destination with your own webhook URL, add an alert, and point the alert at the Discord destination.

## Related Tickets & Documents
N/A

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image

### CODE REVIEW

**Comment by justinclift** [comment]
We've been doing some work on updating the dependency libraries, so that's **probably** why this is showing conflicts (pure guess though).  Hopefully that's not too hard to fix. :smile:

---

Discord as an alert destination sounds like a good idea too.  That'll probably be useful for a bunch of people.

That being said, does anyone have ideas on how we could add some kind of testing for it to our automated PR tests (eg our GitHub Actions CI stuff)?

It'd be good to catch any future PRs which break this, at the time of PR submission rather than later on from user reports. :smile:

**Comment by VitalyVakhteev** [comment]
Hey, I added unit tests for the webhook now. It's most likely possible to set up some kind of GitHub Actions for it so it runs automatically during a PR, although I haven't looked at the current Actions setup and the workflows. Also modified the discord.py file again to remove the unnecessary name/bot_name option.

**Comment by justinclift** [comment]
Ahhh.  Different commit history between the two repos, but the same `master` branch is getting referred to by the PR in each one.

... and it's not gone well for the PR here. :innocent: 

I've not seen that done before, so this is a "Oh, that's what happens when you do that..." learning moment for me. :smile:

**Comment by justinclift** [comment]
Closing this PR in this fork, as it's having major issues due to sharing the same `master` branch as the other repo.  We could look at adding a new PR for the change to this repo later on at some point, if it turns out to be needed.

**Pull request closed without merging**
